name: Deploy
on: 
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Run remote deploy script
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      JWT_SECRET: ${{ secrets.SEC }}
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          SCRIPT: docker compose up -d
          ENVS: TG_TOKEN,JWT_SECRET
