name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: cd TelegramBotApi && dotnet restore
    - name: Build
      run: cd TelegramBotApi && dotnet build --configuration Release --no-restore
    - name: Ssl
      run: sed -i -e "s|^MinProtocol = .*|MinProtocol = TLSv1.0|g" "/etc/ssl/openssl.cnf"
    - name: Test
      run: cd TelegramBotApi && dotnet test --no-restore --verbosity normal
