name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: cd TelegramBotApi && dotnet restore
    - name: Build
      run: cd TelegramBotApi && dotnet build --configuration Release --no-restore
    - name: Test
      env:
        OPENSSL_CONF: ${{ github.workspace }}/ssl.cnf
      run: echo -e "openssl_conf = openssl_init\n[openssl_init]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nOptions = UnsafeLegacyRenegotiation" > ${{ github.workspace }}/ssl.cnf && cd TelegramBotApi && dotnet test --no-restore --verbosity normal
